server:
  port: 80
# Mysql
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop
    username: root
    password: 1234
  # 실행되는 쿼리 콘솔 출력
  jpa:
    show-sql: true
    # 데이터베이스 초기화 전략
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
